import connectToDatabase from '@/lib/mongodb';
import Product from '@/models/Product';

const sampleProducts = [
  {
    name: 'Golden Maharani Necklace',
    slug: 'golden-maharani-necklace',
    category: 'Necklaces',
    description: 'A statement bridal necklace adorned with American Diamond and gold-plated detailing.',
    material: 'Gold-plated Brass',
    price: 2599,
    discountPrice: 1999,
    images: [
      'https://placehold.co/600x600?text=Necklace+1',
      'https://placehold.co/600x600?text=Necklace+1+Side',
    ],
    stock: 18,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.8,
    numReviews: 12,
    reviews: [],
    metaTitle: 'Golden Maharani Necklace | Bridal Jewelry',
    metaDescription: 'Elegant gold-plated bridal necklace with American Diamond accents for a premium wedding look.',
  },
  {
    name: 'Silver Teardrop Earrings',
    slug: 'silver-teardrop-earrings',
    category: 'Earrings',
    description: 'Classic sterling silver earrings with teardrop design and polished finish.',
    material: '925 Sterling Silver',
    price: 1299,
    images: [
      'https://placehold.co/600x600?text=Earrings+1',
      'https://placehold.co/600x600?text=Earrings+1+Detail',
    ],
    stock: 30,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.6,
    numReviews: 8,
    reviews: [],
    metaTitle: 'Silver Teardrop Earrings | Sterling Silver Jewelry',
    metaDescription: 'Lightweight and elegant teardrop earrings crafted from 925 sterling silver.',
  },
  {
    name: 'Rose Gold Halo Ring',
    slug: 'rose-gold-halo-ring',
    category: 'Rings',
    description: 'A dazzling ring set with simulated American Diamond in a rose gold finish.',
    material: 'American Diamond',
    price: 1799,
    discountPrice: 1499,
    images: [
      'https://placehold.co/600x600?text=Ring+1',
      'https://placehold.co/600x600?text=Ring+1+Closeup',
    ],
    stock: 24,
    isFeatured: true,
    isNewArrival: true,
    rating: 4.9,
    numReviews: 20,
    reviews: [],
    metaTitle: 'Rose Gold Halo Ring | Statement Ring',
    metaDescription: 'Fashion ring in rose gold with sparkling American Diamond crystals for a luxe finish.',
  },
  {
    name: 'Pearl Charm Bracelet',
    slug: 'pearl-charm-bracelet',
    category: 'Bangles & Bracelets',
    description: 'A delicate bracelet combining pearls and gold-plated accents for everyday wear.',
    material: 'Pearl',
    price: 1099,
    images: [
      'https://placehold.co/600x600?text=Bracelet+1',
      'https://placehold.co/600x600?text=Bracelet+1+Detail',
    ],
    stock: 15,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.4,
    numReviews: 5,
    reviews: [],
    metaTitle: 'Pearl Charm Bracelet | Elegant Bracelet',
    metaDescription: 'Pearl charm bracelet with gold-plated links for a refined everyday look.',
  },
  {
    name: 'Classic Mangalsutra Set',
    slug: 'classic-mangalsutra-set',
    category: 'Mangalsutra',
    description: 'Traditional mangalsutra with black beads and gold-plated pendant for weddings.',
    material: 'Gold-plated Brass',
    price: 3199,
    images: [
      'https://placehold.co/600x600?text=Mangalsutra+1',
      'https://placehold.co/600x600?text=Mangalsutra+1+Pendant',
    ],
    stock: 8,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.7,
    numReviews: 14,
    reviews: [],
    metaTitle: 'Classic Mangalsutra Set | Wedding Jewelry',
    metaDescription: 'Beautiful mangalsutra with black beads and gold-plated pendant for the perfect bridal accessory.',
  },
  {
    name: 'Silver Anklet with Bells',
    slug: 'silver-anklet-with-bells',
    category: 'Anklets',
    description: 'A playful anklet crafted in sterling silver with delicate bell charms.',
    material: '925 Sterling Silver',
    price: 999,
    images: [
      'https://placehold.co/600x600?text=Anklet+1',
      'https://placehold.co/600x600?text=Anklet+1+Closeup',
    ],
    stock: 22,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.3,
    numReviews: 6,
    reviews: [],
    metaTitle: 'Silver Anklet with Bells | Stylish Anklet',
    metaDescription: 'Delicate sterling silver anklet with charming bell details for festive wear.',
  },
  {
    name: 'Minimal Nose Pin',
    slug: 'minimal-nose-pin',
    category: 'Nose Pins',
    description: 'A minimal nose pin in gold-plated finish with a polished round stud.',
    material: 'Gold-plated Brass',
    price: 499,
    images: [
      'https://placehold.co/600x600?text=Nose+Pin+1',
    ],
    stock: 40,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.1,
    numReviews: 10,
    reviews: [],
    metaTitle: 'Minimal Nose Pin | Daily Wear Nose Pin',
    metaDescription: 'Everyday nose pin with a subtle gold-plated finish for a chic look.',
  },
  {
    name: 'Bridal Combo Set',
    slug: 'bridal-combo-set',
    category: 'Combos & Sets',
    description: 'A coordinated set featuring necklace, earrings, and bracelet in American Diamond.',
    material: 'American Diamond',
    price: 4999,
    discountPrice: 4299,
    images: [
      'https://placehold.co/600x600?text=Combo+Set+1',
      'https://placehold.co/600x600?text=Combo+Set+1+Earrings',
    ],
    stock: 10,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.9,
    numReviews: 22,
    reviews: [],
    metaTitle: 'Bridal Combo Set | Jewelry Set',
    metaDescription: 'Complete bridal set with matching necklace, earrings, and bracelet in a luxe finish.',
  },
  {
    name: 'Kundan Pearl Necklace',
    slug: 'kundan-pearl-necklace',
    category: 'Necklaces',
    description: 'A heritage-inspired Kundan necklace with cultured pearl drops and intricate detailing.',
    material: 'Kundan',
    price: 3799,
    images: [
      'https://placehold.co/600x600?text=Necklace+2',
    ],
    stock: 12,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.5,
    numReviews: 9,
    reviews: [],
    metaTitle: 'Kundan Pearl Necklace | Elegant Necklace',
    metaDescription: 'Traditional Kundan necklace with pearl embellishments for an elegant statement.',
  },
  {
    name: 'Diamond Stud Earrings',
    slug: 'diamond-stud-earrings',
    category: 'Earrings',
    description: 'Stud earrings with sparkling stones set in a high-polish sterling silver frame.',
    material: 'American Diamond',
    price: 1499,
    images: [
      'https://placehold.co/600x600?text=Earrings+2',
    ],
    stock: 28,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.7,
    numReviews: 19,
    reviews: [],
    metaTitle: 'Diamond Stud Earrings | Classic Earrings',
    metaDescription: 'Classic stud earrings with bright simulated diamonds for an everyday sparkle.',
  },
  {
    name: 'Stackable Gold Ring',
    slug: 'stackable-gold-ring',
    category: 'Rings',
    description: 'A modern stackable ring in warm gold finish, perfect for layering.',
    material: 'Gold-plated Brass',
    price: 699,
    images: [
      'https://placehold.co/600x600?text=Ring+2',
    ],
    stock: 50,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.2,
    numReviews: 4,
    reviews: [],
    metaTitle: 'Stackable Gold Ring | Fashion Ring',
    metaDescription: 'Minimal stackable ring with a polished gold-plated finish for versatile styling.',
  },
  {
    name: 'Multi-strand Bracelet',
    slug: 'multi-strand-bracelet',
    category: 'Bangles & Bracelets',
    description: 'A trendy multi-strand bracelet featuring mixed metal links and crystal accents.',
    material: 'American Diamond',
    price: 1399,
    discountPrice: 1199,
    images: [
      'https://placehold.co/600x600?text=Bracelet+2',
    ],
    stock: 20,
    isFeatured: true,
    isNewArrival: true,
    rating: 4.6,
    numReviews: 11,
    reviews: [],
    metaTitle: 'Multi-strand Bracelet | Trendy Bracelet',
    metaDescription: 'Fashion bracelet with layered strands and crystal accents for a bold look.',
  },
  {
    name: 'Minimal Mangalsutra Pendant',
    slug: 'minimal-mangalsutra-pendant',
    category: 'Mangalsutra',
    description: 'A subtle mangalsutra pendant designed for daily wear with a modern twist.',
    material: 'Gold-plated Brass',
    price: 2299,
    images: [
      'https://placehold.co/600x600?text=Mangalsutra+2',
    ],
    stock: 13,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.4,
    numReviews: 7,
    reviews: [],
    metaTitle: 'Minimal Mangalsutra Pendant | Daily Mangalsutra',
    metaDescription: 'Contemporary mangalsutra pendant with black beads and a simple gold-plated charm.',
  },
  {
    name: 'Boho Pearl Anklet',
    slug: 'boho-pearl-anklet',
    category: 'Anklets',
    description: 'A bohemian anklet with freshwater pearl beads and gold-toned chain links.',
    material: 'Pearl',
    price: 899,
    images: [
      'https://placehold.co/600x600?text=Anklet+2',
    ],
    stock: 17,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.3,
    numReviews: 5,
    reviews: [],
    metaTitle: 'Boho Pearl Anklet | Pearl Anklet',
    metaDescription: 'Freshwater pearl anklet with boho-inspired styling for casual outfits.',
  },
  {
    name: 'Floral Nose Pin',
    slug: 'floral-nose-pin',
    category: 'Nose Pins',
    description: 'A pretty floral nose pin in gold-plated brass with tiny stone detailing.',
    material: 'Gold-plated Brass',
    price: 549,
    images: [
      'https://placehold.co/600x600?text=Nose+Pin+2',
    ],
    stock: 36,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.5,
    numReviews: 9,
    reviews: [],
    metaTitle: 'Floral Nose Pin | Stud Nose Pin',
    metaDescription: 'Lovely floral nose pin with gold plating and subtle sparkling stones.',
  },
  {
    name: 'Gold Plated Necklace Set',
    slug: 'gold-plated-necklace-set',
    category: 'Combos & Sets',
    description: 'Matching necklace and earrings set with gold-plated finish and intricate design.',
    material: 'Gold-plated Brass',
    price: 2999,
    images: [
      'https://placehold.co/600x600?text=Combo+Set+2',
    ],
    stock: 9,
    isFeatured: true,
    isNewArrival: true,
    rating: 4.7,
    numReviews: 13,
    reviews: [],
    metaTitle: 'Gold Plated Necklace Set | Jewelry Combo',
    metaDescription: 'Coordinated necklace and earrings set in a rich gold-plated finish.',
  },
  {
    name: 'Pearl Drop Earrings',
    slug: 'pearl-drop-earrings',
    category: 'Earrings',
    description: 'Elegant pearl drop earrings with a chic and timeless silhouette.',
    material: 'Pearl',
    price: 1599,
    images: [
      'https://placehold.co/600x600?text=Earrings+3',
    ],
    stock: 14,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.4,
    numReviews: 7,
    reviews: [],
    metaTitle: 'Pearl Drop Earrings | Classic Earrings',
    metaDescription: 'Classic pearl drop earrings for refined styling and special occasions.',
  },
  {
    name: 'Oxidized Statement Ring',
    slug: 'oxidized-statement-ring',
    category: 'Rings',
    description: 'Bold oxidized ring with floral engraving and antique-inspired styling.',
    material: '925 Sterling Silver',
    price: 1299,
    images: [
      'https://placehold.co/600x600?text=Ring+3',
    ],
    stock: 21,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.5,
    numReviews: 10,
    reviews: [],
    metaTitle: 'Oxidized Statement Ring | Silver Ring',
    metaDescription: 'Antique-style oxidized ring with a striking floral motif for statement looks.',
  },
  {
    name: 'Festive Bangle Pair',
    slug: 'festive-bangle-pair',
    category: 'Bangles & Bracelets',
    description: 'A pair of festive bangles with ornate detailing and gold-plated accents.',
    material: 'Gold-plated Brass',
    price: 1899,
    images: [
      'https://placehold.co/600x600?text=Bracelet+3',
    ],
    stock: 11,
    isFeatured: false,
    isNewArrival: false,
    rating: 4.5,
    numReviews: 8,
    reviews: [],
    metaTitle: 'Festive Bangle Pair | Party Bangles',
    metaDescription: 'Set of two festive bangles with intricate gold-plated detailing.',
  },
  {
    name: 'Traditional Anklet Set',
    slug: 'traditional-anklet-set',
    category: 'Anklets',
    description: 'A traditional anklet set with dual chains and elegant beadwork.',
    material: 'Gold-plated Brass',
    price: 1099,
    images: [
      'https://placehold.co/600x600?text=Anklet+3',
    ],
    stock: 16,
    isFeatured: true,
    isNewArrival: false,
    rating: 4.6,
    numReviews: 10,
    reviews: [],
    metaTitle: 'Traditional Anklet Set | Silver Anklet',
    metaDescription: 'Traditional anklet set with detailed beadwork and layered styling.',
  },
  {
    name: 'Pearl & Stone Nose Pin',
    slug: 'pearl-stone-nose-pin',
    category: 'Nose Pins',
    description: 'A decorative nose pin combining pearl and stone embellishments.',
    material: 'Pearl',
    price: 649,
    images: [
      'https://placehold.co/600x600?text=Nose+Pin+3',
    ],
    stock: 29,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.2,
    numReviews: 6,
    reviews: [],
    metaTitle: 'Pearl & Stone Nose Pin | Designer Nose Pin',
    metaDescription: 'Stylish nose pin with pearl and stone detailing for festive looks.',
  },
  {
    name: 'Eternal Love Set',
    slug: 'eternal-love-set',
    category: 'Combos & Sets',
    description: 'A romantic set with heart-themed necklace and matching earrings.',
    material: 'American Diamond',
    price: 3899,
    images: [
      'https://placehold.co/600x600?text=Combo+Set+3',
      'https://placehold.co/600x600?text=Combo+Set+3+Earrings',
    ],
    stock: 7,
    isFeatured: false,
    isNewArrival: true,
    rating: 4.8,
    numReviews: 16,
    reviews: [],
    metaTitle: 'Eternal Love Set | Jewelry Gift Set',
    metaDescription: 'Beautiful heart-themed jewelry set with necklace and earrings in one package.',
  },
];

export async function GET() {
  if (process.env.NODE_ENV !== 'development') {
    return new Response('Seed route is only available in development.', { status: 403 });
  }

  await connectToDatabase();

  try {
    const existingSlugs = sampleProducts.map((product) => product.slug);
    const existingCount = await Product.countDocuments({ slug: { $in: existingSlugs } });

    if (existingCount > 0) {
      return new Response('Sample products already exist in the database.', { status: 200 });
    }

    await Product.insertMany(sampleProducts);
    return new Response('Seeded 20 sample jewelry products.', { status: 201 });
  } catch (error) {
    return new Response(`Seed failed: ${error.message}`, { status: 500 });
  }
}
